###########################################################
#   Description: Refresh Release API                      #
#   Author: Hyy2001X                                      #
###########################################################

name: Refresh API

on:
  workflow_dispatch:
    inputs:
      refresh_switch:
        description: '手动刷新API'
        default: 'true'
      RELEASE_TAG:
        description: 'TAG名称'
        required: true
        default: 'AutoUpdate-x86-lxc'
        type: choice
        options:
          - 'AutoUpdate-x86-lxc'
          - 'AutoUpdate-x86'
          - 'AutoUpdate-lxc'
          - 'AutoUpdate'
      GITHUB_API:
        description: 'Github api文件名称'
        required: true
        default: 'zzz_api'
        type: choice
        options:
          - 'zzz_api'
          - 'github_api'
          - 'Github_Tags'

env:
  GITHUB_REPOSITORY_URL: https://github.com/${{github.repository}}
  GITHUB_REPOSITORY: ${{github.repository}}
  GITHUB_ACTOR: ${{github.actor}}
  GITHUB_WORKFLOW: ${{github.workflow}}
  
jobs:
  Job:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Github Release API
      id: download
      run: |
        mkdir -p Github_Api
        cd Github_Api
        curl -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" https://api.github.com/repos/${{github.repository}}/releases/tags/${{ github.event.inputs.RELEASE_TAG }} -o ${{ github.event.inputs.GITHUB_API }}
        if [[ $? -ne 0 ]]; then
            wget -q --no-cookie --no-check-certificate https://api.github.com/repos/${{github.repository}}/releases/tags/${{ github.event.inputs.RELEASE_TAG }} -O ${{ github.event.inputs.GITHUB_API }}
        fi

    - name: Upload API to Github Release
      uses: ncipollo/release-action@main
      if: steps.download.outcome == 'success'
      with:
        allowUpdates: true
        token: ${{ secrets.REPO_TOKEN }}
        tag: ${{ github.event.inputs.RELEASE_TAG }}
        artifacts: "Github_Api/*"

    - name: 清理Actions
      if: env.REPO_TOKEN
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{github.repository}}
          keep_minimum_runs: 7
          retain_days: 7
