###########################################################
#   Description: Refresh Release API                      #
#   Author: Hyy2001X                                      #
###########################################################

name: Refresh API

on:
  workflow_dispatch:
    inputs:
      refresh_switch:
        description: '手动刷新API'
        default: 'true'
      tag_name:
        description: 'TAG名称'
        required: true
        default: 'AutoUpdate-lxc'
        type: choice
        options:
          - 'AutoUpdate-lxc'
          - 'AutoUpdate'    

jobs:
  Job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Github Release API
      run: |
        wget https://api.github.com/repos/${{github.repository}}/releases/tags/${{ github.event.inputs.tag_name }} -O Github_Tags
        
    - name: Upload API to Github Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Github_Tags
        file_glob: true
        tag: ${{ github.event.inputs.tag_name }}
        overwrite: true

    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
