###########################################################
#   Description: Refresh Release API                      #
#   Author: Hyy2001X                                      #
###########################################################

name: Refresh API

on:
  workflow_dispatch:
    inputs:
      refresh_switch:
        description: '手动刷新API'
        default: 'true'
      TAG_NAME:
        description: 'TAG名称'
        required: true
        default: 'AutoUpdate-x86-lxc'
        type: choice
        options:
          - 'AutoUpdate-x86-lxc'
          - 'AutoUpdate-x86'
          - 'AutoUpdate-lxc'
          - 'AutoUpdate'
      GITHUB_API:
        description: 'Github api文件名称'
        required: true
        default: 'AutoUpdate-x86-lxc'
        type: choice
        options:
          - 'AutoUpdate-x86-lxc'
          - 'AutoUpdate-x86'
          - 'AutoUpdate-lxc'
          - 'AutoUpdate'
env:
  GITHUB_REPOSITORY_URL: https://github.com/${{github.repository}}
  GITHUB_REPOSITORY: ${{github.repository}}
  GITHUB_ACTOR: ${{github.actor}}
  GITHUB_WORKFLOW: ${{github.workflow}}
  
jobs:
  Job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Github Release API
      run: |
        wget https://api.github.com/repos/${{github.repository}}/releases/tags/${{ github.event.inputs.TAG_NAME }} -O ${{ github.event.inputs.GITHUB_API }}
        
    - name: Upload API to Github Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Github_Tags
        file_glob: true
        tag: ${{ github.event.inputs.TAG_NAME }}
        overwrite: true

    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
